cs253/accounts/urls.py
from django.urls import path
from . import views
from .views import (Sell_Create,Sell_List,Sell_Details,Sell_Delete, Sell_Update)
from django.contrib.auth.decorators import login_required

app_name = 'accounts'

#Urls for redrection to different web pages
urlpatterns = [
    path('', views.home, name="home"),
	path('register/', views.registerPage, name="register"),
	path('login/', views.loginPage, name="login"),  
	path('logout/', views.logoutUser, name="logout"),
	path('buy/',login_required(Sell_List.as_view()), name="buy"),
	path('search/',views.search, name="search"),
	path('sell/',views.Sell_Create, name="sell"),
	path('sell_detail/<int:pk>',Sell_Details.as_view(), name="item_details"),
	# path('rent/', views.rent, name="rent"), 
	path('enterRoom/', views.enterRoom, name="enterRoom"), 
	path('<str:room>/', views.room, name='room'),
    path('enterRoom/checkview', views.checkview, name='checkview'),
    path('send', views.send, name='send'),
    path('getMessages/<str:room>/', views.getMessages, name='getMessages'),
	path('delete/<int:pk>',login_required(Sell_Delete.as_view()), name='delete_item'),
	path('update/<int:pk>',login_required(Sell_Update.as_view()), name='update_item'),
]

cs253/crm1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  
from django.conf.urls.static import static  
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls'))

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) 

cs253/accounts/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
# Create your models here.


#This is a model that can be used if more developments in this project are made in future
# class Customer(models.Model):  #This model is used to define a buyer
#         name = models.CharField(max_length=100,null=True)
#         user = models.OneToOneField(User,null=True,on_delete=models.CASCADE)
#         date_created = models.DateTimeField(auto_now_add=True)
#         phone = models.IntegerField(default=0)

#         def __str__(self):
#             return self.name


#This is a model that can be used if more developments in this project are made in future
# class Seller(models.Model): #This model is used to define a seller
#         name = models.CharField(max_length=100,null=True)
#         user = models.OneToOneField(User,null=True,on_delete=models.CASCADE)
#         date_created = models.DateTimeField(auto_now_add=True)
#         phone = models.IntegerField(default=0)

#         def __str__(self):
#             return self.name

class Sell(models.Model): #This model is used to define a product to be traded of
    name = models.CharField(max_length=40,null=True)
    description = models.TextField(max_length=200,null=True)
    photo = models.ImageField(null=True,blank=True,upload_to="images/")
    price = models.IntegerField()
    seller = models.ForeignKey(User,null=True,on_delete=models.SET_NULL)

    def __str__(self):
        return self.name
    

#This is a model that can be used if more developments in this project are made in future
# class Order(models.Model): #
#     product = models.OneToOneField(Sell,null=True,on_delete=models.SET_NULL)
#     customer = models.ForeignKey(Customer,null=True,on_delete=models.SET_NULL)
#     date_ordered = models.DateTimeField(auto_now_add=True)

#     def __str__(self):
#         return self.product

class Room(models.Model): #This model is used to define a new chatroom
    name = models.CharField(max_length=1000,unique=True)

class Message(models.Model): #This model is used to maintain the chats of different users in different product chatboxes
    value = models.CharField(max_length=1000000)
    date = models.DateTimeField(default=datetime.now, blank=True)
    user = models.CharField(max_length=1000000)
    room = models.CharField(max_length=1000000)

cs253/accounts/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Sell

class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']
  

class Sell_form(ModelForm):
	class Meta:
		model = Sell
		fields = ['name', 'description', 'photo', 'price']

cs253/accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.forms import inlineformset_factory
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, DeleteView, UpdateView
from django.contrib.auth import authenticate, login, logout
import math
from django.contrib import messages
from django.db.models.signals import post_delete
from django.contrib.messages.views import SuccessMessageMixin
import json
from django.contrib.auth.models import User
from django.contrib import messages
from accounts.models import Room, Message
from django.http import HttpResponse, JsonResponse

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
# Create your views here.
from .models import Sell
from .forms import CreateUserForm, Sell_form

def registerPage(request): #This is used to redirect the user to register page so to register a new user
    if request.user.is_authenticated:
        return redirect('accounts:home')
    else:
        form = CreateUserForm()
        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request, 'Account was created for ' + user)

                return redirect('accounts:login')

        context = {'form': form}
        return render(request, 'accounts/register.html', context)


def loginPage(request): #This is used to redirect the user to login page
    if request.user.is_authenticated:
        return redirect('accounts:home')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('accounts:home')
            else:
                messages.info(request, 'Username OR password is incorrect')

        context = {}
        return render(request, 'accounts/login.html', context)


def logoutUser(request): #To logout the user
    logout(request)
    return redirect('accounts:login')


@login_required(login_url='accounts:login')
def home(request):   #This is used to redirect logged in user to Home page and send the product list of items uploaded by that used to that page
    products = Sell.objects.filter(seller=request.user)
    print(products)
    n = len(products)
    print(n)
    nSlides= n
    parameters={'no_of_slides':nSlides, 'range':range(1,nSlides), 'products': products}
    return render(request, 'accounts/home.html', parameters)



def searchMatch(query, item):  #Returns true if a product satisfies the search query and false otherwise
	if(query.lower() in item.name.lower() or query.lower() in item.description.lower()):
		return True
	return False

@login_required(login_url='accounts:login')
def search(request): #Algorithm to search for a product
	query = request.GET['search']
	products_temp = Sell.objects.all(); list = Sell.objects.filter(seller=request.user)
	products = [item for item in products_temp if searchMatch(query, item) and item not in list]
	# products = Sell.objects.filter(title__icontains=query)
	return render(request, 'accounts/search.html', {'products': products})


# @login_required(login_url='accounts:login')
# def rent(request): #Function to send product list to rent page and then redirect to rent page
#     context = {}
#     return render(request, 'accounts/rent.html', context)

@login_required(login_url='accounts:login')
def Sell_Create(request): # Function to add a new product by taking input from the sell form page
    form = Sell_form(request.POST, request.FILES)
    u_list = User.objects.all()
    if request.method == 'POST':
        name = request.POST['name']
        description = request.POST['description']
        photo = request.FILES['photo']
        price = request.POST['price']
        seller = request.user
        if name=='' or description=='' or price=='' or seller=='':
            messages.success(request,'Kindly fill all the fields.')
            return render(request,'accounts/home.html')
        Sell.objects.create(name=name, description=description, photo=photo, price=price, seller = seller)
        return redirect('accounts:home')
    return render(request, 'accounts/sell_form.html', {'form': form, 'u_list': u_list})


class Sell_List(ListView): #Class to send product list to buy page and then redirect to buy page
    model = Sell
    context_object_name = 'item_list'
    def get_queryset(self):
        return Sell.objects.exclude(seller=self.request.user)


class Sell_Details(DetailView): #Class to redirect to product details page
    model = Sell


#All the below functions are used for chatroom functionality

@login_required(login_url='accounts:login')
def enterRoom(request): #Function to redirect to the chatroom
    return render(request, 'accounts/enterRoom.html')


@login_required(login_url='accounts:login')
def room(request, room): #Return details related to chatroom of a specific product
    username = str(request.user)
    room_details = Room.objects.get(name=room)
    return render(request, 'accounts/room.html', {
        'username': username,
        'room': room,
        'room_details': room_details
    })


def checkview(request):
    jsonResponse=json.loads(request.body)
    room = jsonResponse['room_name']
    username = str(request.user)

    if Room.objects.filter(name=room).exists():
        return redirect('/'+room+'/?username='+username)
    else:
        new_room = Room.objects.create(name=room)
        new_room.save()
        return redirect('/'+room+'/?username='+username)

def send(request): #Function to make create new chat
    message = request.POST['message']
    username = request.POST['username']
    room_id = request.POST['room_id']

    new_message = Message.objects.create(value=message, user=username, room=room_id)
    new_message.save()
    return HttpResponse('Message sent successfully')

def getMessages(request, room): #Functon to get older messages in that product chatbox
    room_details = Room.objects.get(name=room)

    messages = Message.objects.filter(room=room_details.id)
    return JsonResponse({"messages":list(messages.values())})

class Sell_Delete(DeleteView):
    model = Sell
    success_url = reverse_lazy('accounts:home')

'''class Sell_Update(UpdateView):
    model = Sell
    fields = ['name', 'description', 'photo', 'price']
    success_url = reverse_lazy('accounts:home')'''
    

class Sell_Update(UpdateView):
    model = Sell
    form_class = Sell_form
    initial = {}
    success_url = reverse_lazy('accounts:home')

cs253/accounts/templates/accounts/dashboard.html
{%  extends 'accounts/main.html' %}

{% block content %}
{% load static %}
<div class="card" style="margin:15px; background-color:#E0FFFF;">
  <div class="card-body">
    <h5 class="card-title">BUY Different Products</h5>
    <p class="card-text">You can directly have <b>CHAT</b> with the seller to purchase variety items at affordable prices on SINGLE click...</p>
    <a href="{% url 'accounts:buy' %}" class="btn btn-success">View Products</a>
  </div>
</div>
{% if products %}
<h4 style="margin:20px">Items Uploaded by You: </h4>
<hr>

<div class="container">
    <div class="row">
{% for item in products %}
            <div class="card" style="width: 15rem; margin: 15px 15px; border: 5px solid black; border-radius: 8px;background-color:#E0FFFF;">
                <a href="/sell_detail/{{item.id}}"><img class="card-img-top" src="{{item.photo.url}}" alt="Card image cap"
                style="width: 230px; height: 220px">
                <div class="card-body">
                  <h5 class="card-title" style="color:black;">{{item.name}}</h5>
                  <p class="card-text" style="color:black;"> Price: &#8377; {{item.price}} <br> {{item.description}}</p>
                </div>
                </a>
                <div class="card-footer">      
                  <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
                    <div class="btn-group btn-group-sm btn-group mr-1" role="group" aria-label="First group">
                    <a class="btn btn-success" href="/update/{{item.id}}">Update</a> 
                    </div>
                    <div class="btn-group btn-group-sm btn-group mr-1" role="group" aria-label="Second group">
                    <a class="btn btn-danger" href="/delete/{{item.id}}">Delete</a>
                    </div>
                    <div class="btn-group btn-group-sm btn-group mr-1" role="group" aria-label="Third group">
                    <a href="#" class="btn btn-info" onclick="joinRoom('{{item.name}}','{{item.id}}')">Chat</a>
                    </div>
                  </div>
                </div>
              </div>
{% endfor %}
            </div>
        </div>
        <div class="card border-success mb-3">
          <div class="card text-center">
            <div class="card-body" style="background-color:#E0FFFF;" >
              <h3 class="card-title">You can add more products by visiting the link below</h3>
              <a href="{% url 'accounts:sell' %}" class="btn btn-success">Add Product</a>
            </div>
          </div>
        </div>
{% else %}
<h4 style="margin:20px">Items Uploaded by You: </h4>
<hr>
<p>You have not uploaded any items for sell...</p>
<div class="card border-success mb-3" style="margin:15px;">
  <div class="card text-center">
    <div class="card-body" style="background-color:#E0FFFF;" >
      <h3 class="card-title">You can also Sell your product at single click !</h3>
      <p class="card-text">Upload the details of your product by clicking below.</p>
      <a href="{% url 'accounts:sell' %}" class="btn btn-success">Sell Your Product</a>
    </div>
  </div>
</div>
{% endif %}

<script>
    function getCookie(c_name) {
      var c_arr = document.cookie.split(';');
      var jwtToken
      c_arr.forEach((val) => {
        if (c_name == val.split('=')[0]) {
          var token = val.split('=')[1];
          jwtToken = token
        }
      })
      return decodeURI(jwtToken);
    }
  
    function joinRoom(room, id) {
      const body = {
        room_name: 'Room '+id
      }
      console.log(body)
      fetch("http://127.0.0.1:8000/enterRoom/checkview", {
        method: "POST",
        headers: {
          'Content-Type': 'application/json',
          'X-CSRFToken': getCookie('csrftoken'),
          'authority': 'bearer ' + getCookie('csrftoken')
        },
        body: JSON.stringify(body)
      }
      ).then((response) => {
        // console.log(response.url)
        window.location = response.url
      })
    }
  </script>
 {% endblock %}

cs253/accounts/templates/accounts/enterRoom.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  margin: 0 auto;
  max-width: 800px;
  padding: 0 20px;
}

.container {
  border: 2px solid #dedede;
  background-color: #f1f1f1;
  border-radius: 5px;
  padding: 10px;
  margin: 10px 0;
}

.darker {
  border-color: #ccc;
  background-color: #ddd;
}

.container::after {
  content: "";
  clear: both;
  display: table;
}

.container img {
  float: left;
  max-width: 60px;
  width: 100%;
  margin-right: 20px;
  border-radius: 50%;
}

.container img.right {
  float: right;
  margin-left: 20px;
  margin-right:0;
}

.time-right {
  float: right;
  color: #aaa;
}

.time-left {
  float: left;
  color: #999;
}
</style>
</head>
<body>

<div textalign="center">
    <h2>Django Chat</h2>
</div>


<div class="container">
    <style>
    input[type=text], select {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
    }

    input[type=submit] {
    width: 100%;
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    }

    input[type=submit]:hover {
    background-color: #45a049;
    }

    div {
    border-radius: 5px;
    background-color: #f2f2f2;
    padding: 20px;
    }
    </style>

    <form id="post-form" method="POST" action="checkview">
        {% csrf_token %}
        <label>Room Name</label>
        <input type="text" name="room_name" id="room_name" width="100px" />
        <input type="submit" value="Enter Room">
    </form>
</div>


</body>


</html>

cs253/accounts/templates/accounts/footer.html
<footer class="page-footer font-small unique-color-dark" style="background-color: rgb(61, 51, 51); color: white; padding: 10px;">

    <!-- Footer Links -->
    <div class="container text-center text-md-left mt-5">
  
      <!-- Grid row -->
      <div class="row mt-3">
  
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
  
          <!-- Content -->
          <h6 class="text-uppercase font-weight-bold">IITKart</h6>
          <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
          <p>This website was made in 2022 with the aim of helping students of IIT Kanpur.
          </p>
  
        </div>
        <!-- Grid column -->
  
        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
  
          <!-- Links -->
          <h6 class="text-uppercase font-weight-bold">Feedback</h6>
          <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
          <p>
            <a href="https://docs.google.com/forms/d/e/1FAIpQLSdaxpjTx1Ul24Xa-1HB52q69aGOL9bXf0aKQ7_8yhbL8N1qUw/viewform?usp=sf_link">Give us Suggestions</a>
          </p>
  
        </div>
        <!-- Grid column -->
  
        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
  
          <!-- Links -->
          <h6 class="text-uppercase font-weight-bold">Useful links</h6>
          <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
          <p>
            <a href="{%url 'accounts:home'%}">Home</a>
          </p>
          <p>
            <a href="{%url 'accounts:buy'%}">Buy Products</a>
          </p>
          <p>
            <a href="{%url 'accounts:sell'%}">Sell Products</a>
          </p>
        </div>
        <!-- Grid column -->
  
        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
  
          <!-- Links -->
          <h6 class="text-uppercase font-weight-bold">Contact</h6>
          <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
          <p>
            <i class="fas fa-home mr-3"></i> IIT Kanpur, UP 208016, INDIA</p>
          <p>
            <i class="fas fa-envelope mr-3"></i> IITKart@iitk.ac.in</p>
          <p>
            <i class="fas fa-phone mr-3"></i> +91 9949700172</p>
          <p>
            <i class="fas fa-print mr-3"></i> + 91 8612792086</p>
  
        </div>
        <!-- Grid column -->
  
      </div>
      <!-- Grid row -->
  
    </div>
    <!-- Footer Links -->
  
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2022 Copyright:
      <p><b>Team 9 : Matrix</b></p>
    </div>
    <!-- Copyright -->
  
  </footer>

cs253/accounts/templates/accounts/navbar.html
{% load static %}
<style>
</style>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <img src="/media/images/logo_trans.png" alt="logo" width="55px">
<!--     <a class="navbar-brand" href="#">IITKart</a> -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:buy' %}">Buy</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:sell' %}">Sell</a>
        </li>

      </ul>
      {% comment %} <form class="d-flex" action='/search'>
        <div class="input-group">
          <input name='q' type="text" class="form-control" placeholder="Search" />
          <button class="btn btn-outline-success" type="submit" id="button-addon2" style="margin: 0px 5px">Search</button>
        </div> {% endcomment %}

        <form class="d-flex" action='/search'>
          <input name='search' class="form-control me-2" type="search" placeholder="Search" aria-label="Search" style="margin: 0px 5px">
          <button class="btn btn-outline-success" type="submit" style="margin: 0px 5px">Search</button>
        </form>
        
      </form>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link">Hello, {{request.user}}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:logout' %}" style="color: red">Logout</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
</nav>

cs253/accounts/templates/accounts/room.html
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    <style>
       h3{
         text-align: center ;
       }
      .container {
        border: 2px solid #dedede;
        background-color: #f1f1f1;
        border-radius: 5px;
        padding: 10px;
        height: 50% ;
        width: 50% ;
        margin: auto;
      }

      .darker {
        border-color: #ccc;
        background-color: #ddd;
      }

      .container::after {
        content: "";
        clear: both;
        display: table;
      }

      .container img {
        float: left;
        max-width: 60px;
        width: 100%;
        margin-right: 20px;
        border-radius: 50%;
      }

      .container img.right {
        float: right;
        margin-left: 20px;
        margin-right: 0;
      }

      .time-right {
        float: right;
        color: #aaa;
      }

      .time-left {
        float: left;
        color: #999;
      }
    </style>
    <script
      src="https://code.jquery.com/jquery-3.1.1.min.js"
      integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
      crossorigin="anonymous"
    ></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <img src="/media/images/logo_trans.png" alt="logo" width="55px">
    <!--     <a class="navbar-brand" href="#">IITKart</a> -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:buy' %}">Buy</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:sell' %}">Sell</a>
            </li>
    
          </ul>
          {% comment %} <form class="d-flex" action='/search'>
            <div class="input-group">
              <input name='q' type="text" class="form-control" placeholder="Search" />
              <button class="btn btn-outline-success" type="submit" id="button-addon2" style="margin: 0px 5px">Search</button>
            </div> {% endcomment %}
    
            <form class="d-flex" action='/search'>
              <input name='search' class="form-control me-2" type="search" placeholder="Search" aria-label="Search" style="margin: 0px 5px">
              <button class="btn btn-outline-success" type="submit" style="margin: 0px 5px">Search</button>
            </form>
            
          </form>
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link">Hello, {{request.user}}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:logout' %}" style="color: red">Logout</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <h2 style="text-align: center;">{{room}}</h2>
    <div id="display"></div>

    <script>
      $(document).ready(function(){

      setInterval(function(){
          $.ajax({
              type: 'GET',
              url : "/getMessages/{{room}}/",
              success: function(response){
                  // console.log(response);
                  $("#display").empty();
                  if (response.messages.length ==0){
                    var temp="<h3>No one has sent message to this room yet.</h3>";
                      $("#display").append(temp);}
                  for (var key in response.messages)
                  {
                      var temp="<div class='container darker'><b>"+response.messages[key].user+"</b><p>"+response.messages[key].value+"</p><span class='time-left'>"+response.messages[key].date+"</span></div>";
                      $("#display").append(temp);
                  }
              },
              error: function(response){
                  alert('An error occurred')
              }
          });
      },1000);
      })
    </script>

    <div class="container">
      <style>
        input[type="text"],
        select {
          width: 100%;
          padding: 12px 20px;
          margin: 8px 0;
          display: inline-block;
          border: 1px solid #ccc;
          border-radius: 4px;
          box-sizing: border-box;
        }

        input[type="submit"] {
          width: 100%;
          background-color: #4caf50;
          color: white;
          padding: 14px 20px;
          margin: 8px 0;
          border: none;
          border-radius: 4px;
          cursor: pointer;
        }

        input[type="submit"]:hover {
          background-color: #45a049;
        }
      </style>

      <form id="post-form">
        {% csrf_token %}
        <input
          type="hidden"
          name="username"
          id="username"
          value="{{username}}"
        />
        <input
          type="hidden"
          name="room_id"
          id="room_id"
          value="{{room_details.id}}"
        />
        <input type="text" name="message" id="message" width="100px" />
        <input type="submit" value="Send" />
      </form>
    </div>
  </body>

  <script type="text/javascript">
    $(document).on("submit", "#post-form", function (e) {
      e.preventDefault();

      $.ajax({
        type: "POST",
        url: "/send",
        data: {
          username: $("#username").val(),
          room_id: $("#room_id").val(),
          message: $("#message").val(),
          csrfmiddlewaretoken: $("input[name=csrfmiddlewaretoken]").val(),
        },
        success: function (data) {
          //alert(data)
        },
      });
      document.getElementById("message").value = "";
    });
  </script>
</html>

cs253/accounts/templates/accounts/sell_confirm_delete.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<form method="POST">
    {% csrf_token %}
    <div style="width:50%; margin:auto; text-align:center;">
    <p style="margin: 5px;"> Are you sure you want to Delete this product ? </p>
    <input type="submit" value="DELETE" class="btn btn-danger btn-sm">
    <a href="{% url 'accounts:home' %}" class="btn btn-success btn-sm" style="margin:0px 5px;">NO</a>
    </div>
</form>